// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MeshServiceStatus struct {
	ServiceUuid          string   `protobuf:"bytes,1,opt,name=service_uuid,json=serviceUuid,proto3" json:"service_uuid,omitempty"`
	ServiceType          string   `protobuf:"bytes,2,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeshServiceStatus) Reset()         { *m = MeshServiceStatus{} }
func (m *MeshServiceStatus) String() string { return proto.CompactTextString(m) }
func (*MeshServiceStatus) ProtoMessage()    {}
func (*MeshServiceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *MeshServiceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshServiceStatus.Unmarshal(m, b)
}
func (m *MeshServiceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshServiceStatus.Marshal(b, m, deterministic)
}
func (m *MeshServiceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshServiceStatus.Merge(m, src)
}
func (m *MeshServiceStatus) XXX_Size() int {
	return xxx_messageInfo_MeshServiceStatus.Size(m)
}
func (m *MeshServiceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshServiceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_MeshServiceStatus proto.InternalMessageInfo

func (m *MeshServiceStatus) GetServiceUuid() string {
	if m != nil {
		return m.ServiceUuid
	}
	return ""
}

func (m *MeshServiceStatus) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

type MeshServiceStatusResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeshServiceStatusResponse) Reset()         { *m = MeshServiceStatusResponse{} }
func (m *MeshServiceStatusResponse) String() string { return proto.CompactTextString(m) }
func (*MeshServiceStatusResponse) ProtoMessage()    {}
func (*MeshServiceStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *MeshServiceStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshServiceStatusResponse.Unmarshal(m, b)
}
func (m *MeshServiceStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshServiceStatusResponse.Marshal(b, m, deterministic)
}
func (m *MeshServiceStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshServiceStatusResponse.Merge(m, src)
}
func (m *MeshServiceStatusResponse) XXX_Size() int {
	return xxx_messageInfo_MeshServiceStatusResponse.Size(m)
}
func (m *MeshServiceStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshServiceStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MeshServiceStatusResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MeshServiceStatus)(nil), "api.MeshServiceStatus")
	proto.RegisterType((*MeshServiceStatusResponse)(nil), "api.MeshServiceStatusResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0x8a, 0xe4, 0x12, 0xf4, 0x4d,
	0x2d, 0xce, 0x08, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x0d, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0x16,
	0x52, 0xe4, 0xe2, 0x29, 0x86, 0x08, 0xc4, 0x97, 0x96, 0x66, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0x71, 0x43, 0xc5, 0x42, 0x4b, 0x33, 0x53, 0x90, 0x95, 0x94, 0x54, 0x16, 0xa4, 0x4a,
	0x30, 0xa1, 0x28, 0x09, 0xa9, 0x2c, 0x48, 0x55, 0x92, 0xe6, 0x92, 0xc4, 0x30, 0x3a, 0x28, 0xb5,
	0xb8, 0x20, 0x3f, 0xaf, 0x38, 0xd5, 0x28, 0x9c, 0x8b, 0x13, 0x24, 0xe9, 0x98, 0x9e, 0x9a, 0x57,
	0x22, 0xe4, 0xc5, 0xc5, 0xe7, 0x5b, 0x09, 0x51, 0x10, 0x5a, 0x90, 0x92, 0x58, 0x92, 0x2a, 0x24,
	0xa6, 0x07, 0x72, 0x27, 0x86, 0x76, 0x29, 0x39, 0xec, 0xe2, 0x30, 0x63, 0x95, 0x18, 0x92, 0xd8,
	0xc0, 0x9e, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb3, 0xb6, 0xc8, 0x10, 0xe9, 0x00, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MeshAgentClient is the client API for MeshAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MeshAgentClient interface {
	MyStatusUpdate(ctx context.Context, in *MeshServiceStatus, opts ...grpc.CallOption) (*MeshServiceStatusResponse, error)
}

type meshAgentClient struct {
	cc *grpc.ClientConn
}

func NewMeshAgentClient(cc *grpc.ClientConn) MeshAgentClient {
	return &meshAgentClient{cc}
}

func (c *meshAgentClient) MyStatusUpdate(ctx context.Context, in *MeshServiceStatus, opts ...grpc.CallOption) (*MeshServiceStatusResponse, error) {
	out := new(MeshServiceStatusResponse)
	err := c.cc.Invoke(ctx, "/api.MeshAgent/MyStatusUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeshAgentServer is the server API for MeshAgent service.
type MeshAgentServer interface {
	MyStatusUpdate(context.Context, *MeshServiceStatus) (*MeshServiceStatusResponse, error)
}

// UnimplementedMeshAgentServer can be embedded to have forward compatible implementations.
type UnimplementedMeshAgentServer struct {
}

func (*UnimplementedMeshAgentServer) MyStatusUpdate(ctx context.Context, req *MeshServiceStatus) (*MeshServiceStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MyStatusUpdate not implemented")
}

func RegisterMeshAgentServer(s *grpc.Server, srv MeshAgentServer) {
	s.RegisterService(&_MeshAgent_serviceDesc, srv)
}

func _MeshAgent_MyStatusUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeshServiceStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshAgentServer).MyStatusUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MeshAgent/MyStatusUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshAgentServer).MyStatusUpdate(ctx, req.(*MeshServiceStatus))
	}
	return interceptor(ctx, in, info, handler)
}

var _MeshAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.MeshAgent",
	HandlerType: (*MeshAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MyStatusUpdate",
			Handler:    _MeshAgent_MyStatusUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
