[API]
Port = 3000

[Persistance]
DataFile = "queuefile.nogit"
NextMessageFile = "nextmessagefile.nogit"
MaxBytes = 1024
MaxUnreadMessages = 1000

[Acknowledgement]

# Minimum secnds to wait for acknowledgement after pop
# before message is re-inserted into the queue.
SecondsBeforeReInsert = 60